### ISSUE TITLE
230324 최종 수정 기획팀 프론트엔드 제안서

### ISSUE THREAD

**Issue by osohyun0224** [Hallym-LIKELION/HallymFestival2023-Frontend#18]
1. **굿즈 안내 페이지 구현 사항**
    1. 기획 의도: 축준위에서 제작한 축제 굿즈들을 소개하고, 바로 구매할 수 있는 안내 구글폼으로 이동할 수 있는 페이지를 제작하고자함.
    2. 자세한 기획 내용: 
        1. 배포 시작~ 축제 전날까지 : 굿즈 **사전 수요 조사** 구글 폼 링크
        2. 축제 기간(3일)  : 굿즈 **구매** 구글 폼 링크
        3. 굿즈 구성: 현재 소주잔, 스티커, 그립톡 외 2개 ( 최종 5개 이하)
    3. 개발 기획안
        

- [x] - About Us 페이지와 유사하게 상품 카드 와 구글 폼 링크만
- [x]         - 상품 카드에는 사진, 상품 명, 가격만 안내됨

        
2. **기획/디자인 팀 디자인 넘겨주는 최종 날짜**
    1.  4/2일까지 모든 피그마 data 전체 넘김
    
3. **부스 상세 페이지 구현 사항**
    1. 댓글 
        1. 요청사항: 
            1. 타인에 대한 비방 시~ 경고 안내 메세지 
            2. 댓글 랜덤 닉네임 형용사 축준위 제공 예정
            3. 부스 소개할때 동아리 소개도 넣어주세요
        2. 기획팀 의견 최종 공지 및 개발 기획안
            

- [ ] 1. 댓글을 쓰는 모달창에 경고문 안내를 넣고, 확인 버튼을 눌러야 댓글을 쓰게 되는 것으로 프론트에게 기획 요청함.

            2. 기획팀장 확인완료
            3. 부스소개에서 동아리 소개도 같이 할 수 있도록 프론트에게 기획 요청함(따로 동아리 소개 입력란 넣지 않음)
    2. 부스 목록 
        1. 기획팀 제안:
            - 부스 목록에서 부스 별로 컬러를 다르게 할 예정입니다
            - 하루 당 부스 적어도 30개가 나올 것 같습니다. 페이징은 넣지 않습니다.
            - 부스별 mbti와, 해시태그를 넣는 것을 삭제할 예정입니다.
    
    1. **메뉴바 구현 사항**
    - 기획팀 제안:
        - 홍보 팀장님의 요청사항이 많아짐에 따라, 메뉴의 항목이 너무 많아져 수정을 요청합니다.
            

- [x] - 현재에서 HOME 항목을 삭제하고, 모든 페이지의 맨 위의 상단 ‘2023 한림대학교 비봉축전’을 누르면 홈화면으로 갈 수 있도록 변경
- [x]             - 메뉴에서 오시는 길을 삭제 (아예 삭제)
 

    
    **4.방명록**
    
    1. 기획팀 제안:
   

- [x]      1. 방명록 글자수를 100자로 제한해주세요

        
    
    **5. 신고기능**
    
    1. 홍보팀장 요청사항: 신고기능 개발자들끼리 결정해주세요
    2. 기획/프론트/백엔드 결정사항:
        

- [ ] 1. 3개 이상의 신고 카운트가 들어가게 되면 , 보여주는 리스트에서 제외하는 것으로 하겠습니다.

        
    
    **6. 홈 화면 하단에 스토리 넣는것**
    
  

- [ ]   1. 홍보팀장님 프론트엔드 요청사항: 동국대랑 똑같이 넣어주세요

**Comment by PortalCube** [comment]
대부분 해결된 문제이므로 닫겠습니다.
