### ISSUE TITLE
design : 디자인 최종 본 반영

### ISSUE THREAD

**Issue by osohyun0224** [Hallym-LIKELION/HallymFestival2023-Frontend#61]
디자인이 차근차근 나오고 있음에 따라 디자인 반영 이슈를 생성하고자 합니다.

**- 일반 유저 페이지**

- [ ] 홈
- [ ] 부스 목록
- [ ] 부스 상세
- [ ] 공지사항
- [ ] 방명록
- [ ] 굿즈
- [ ] 로그인
- [ ] 404
- [ ] 프로그램
- [ ] 타임테이블

**- 백오피스 관리자 페이지**

- [ ] 백오피스 대시보드
- [ ] 백오피스 부스댓글
- [ ] 백오피스 방명록

**Comment by PortalCube** [comment]
완료
