### ISSUE TITLE
프로젝트 기획서/유저리서치 pdf 올려드립니다

### ISSUE THREAD

**Issue by osohyun0224** [Hallym-LIKELION/HallymFestival2023-Frontend#86]
이슈로도 올려드립니다ㅠㅠ 

[한림대학교축제웹페이지기획서_멋쟁이사자.pdf](https://github.com/Hallym-LIKELION/HallymFestival2023-Frontend/files/11220871/_.pdf)
[TalkFile_유저리서치_설문내용.pdf.pdf](https://github.com/Hallym-LIKELION/HallymFestival2023-Frontend/files/11220874/TalkFile_._.pdf.pdf)

**Comment by PortalCube** [comment]
#44 에 통합
